PackageIdentifier: DevZucca.AppLoggers
PackageVersion: 0.2.2
PackageLocale: en-US
Publisher: DevZucca
PackageName: AppLoggers CLI
License: MIT
ShortDescription: AppLoggers telemetry CLI
ManifestType: defaultLocale
ManifestVersion: 1.6.0
