PackageIdentifier: DevZucca.AppLoggerCLI
PackageVersion: 0.1.0
PackageLocale: en-US
Publisher: DevZucca
PackageName: AppLogger CLI
License: Apache-2.0
ShortDescription: AppLogger telemetry CLI
ManifestType: defaultLocale
ManifestVersion: 1.6.0
